name: admin

domain: "admin.uds.dev"

# Development certificate and key *.admin.uds.dev (127.0.0.1)
# Publicly available, not for use in production environments
tls:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIGNjCCBR6gAwIBAgIQAiYjJlL0FbVZMjdXvgxaqzANBgkqhkiG9w0BAQsFADCB
    jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
    A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
    Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
    MB4XDTIzMTAxNzAwMDAwMFoXDTI0MTExNjIzNTk1OVowGjEYMBYGA1UEAwwPKi5h
    ZG1pbi51ZHMuZGV2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmg0
    UuR6/ZA/wDStZ9KFYtVpJDrtC3vOcAujqwqVX3nIEbyDYMYmnqL/FVzCXOemtd6M
    H1YzsiXPMJy4UXe3/QXxtaSx8gf3TBJQVclzp4zV4A91N6PLSEJZ0AOh5omOTrYz
    48TdEVksasltowythWZhavfE8mmDpZr+iZbbES4m9rS1zQayCccabwf3MMpjIpZW
    hiJCiudTKUHkmRNhCGc3cqyyM7e4LH8QRTDj7/54WfVUUVWKMT7FjkMcbtLsgN7X
    Iax0MUL3HCZAJpe9XSkEYhAKPFf546CvivyJsY7OUKq7cWtrihgA75QiW+uzSXL5
    WiAHpGh7dTbZ532cRwIDAQABo4IDADCCAvwwHwYDVR0jBBgwFoAUjYxexFStiuF3
    6Zv5mwXhuAGNYeEwHQYDVR0OBBYEFJ8CGjiSdRrcoeIYDDmnM88gonXfMA4GA1Ud
    DwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
    BgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgIHMCUwIwYIKwYBBQUHAgEW
    F2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECATCBhAYIKwYBBQUHAQEE
    eDB2ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LnNlY3RpZ28uY29tL1NlY3RpZ29S
    U0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCMGCCsGAQUFBzAB
    hhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTApBgNVHREEIjAggg8qLmFkbWluLnVk
    cy5kZXaCDWFkbWluLnVkcy5kZXYwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB3
    AHb/iD8KtvuVUcJhzPWHujS0pM27KdxoQgqf5mdMWjp0AAABizxPrNQAAAQDAEgw
    RgIhAKpiYqs45vUe7SgVrWtDMdGe1gF7q1ZDCOvQrLAZyYj5AiEAxpWNxc4mWccW
    J13+ECh24sfCirQRsVko9aMzGo+8RNQAdQDatr9rP7W2Ip+bwrtca+hwkXFsu1GE
    hTS9pD0wSNf7qwAAAYs8T60mAAAEAwBGMEQCIEJ2sCw/Mk1bTVZIky0JZdAcrSmo
    sN0L/336YPd7Usp0AiBwgATvhROYm9SDHNEKOKJ39F/cuVZxj3dpTILN4epk4QB2
    AO7N0GTV2xrOxVy3nbTNE6Iyh0Z8vOzew1FIWUZxH7WbAAABizxPrPsAAAQDAEcw
    RQIhAK0S6itxp+EasbG9+eCEad1m7X2WwZ45Gkyd9cwqFIo1AiBBz9Ny9m3XB+YV
    ndXZS2VkONEtgLFF3H/0r0IB56s9ITANBgkqhkiG9w0BAQsFAAOCAQEAYoduuqNR
    FlAiO3D3DnMAIa7qU2R/ExBDdcu/iC+nGLBLdLro2SwWdw4ViN17xvUIW/PfEQXp
    Qw5rFnjzp9qmdqM5derZvGJEVkq1knmb5Ah395QXkrnDB6UGVB15KP8jJb3EgSIF
    AqzoaWQPXeH66GNZA70nNWtHMrRhivvV4q4SlK6FBp4uq8KSfThvb82fULTaKPxd
    soQ/0NebOvAhRfYoXlbbu3Wp6rqIe2wgkF69U5/MmC3cKHDBxQ75LQ8ckeqXVHJx
    gHvgSQMkl+O42yvEUzYJ6cBz2d8llVxHdeucjT++v7dgkU5k6T+VF1sTgoh+y+s3
    ONNt9auWOcCpyw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
    iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
    cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
    BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
    MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
    BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
    ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
    VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
    TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
    eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
    oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
    Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
    uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
    BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
    +ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
    CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
    LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
    BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
    bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
    L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
    ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
    7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
    H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
    RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
    xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
    sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
    l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
    6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
    LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
    yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
    00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFgTCCBGmgAwIBAgIQOXJEOvkit1HX02wQ3TE1lTANBgkqhkiG9w0BAQwFADB7
    MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD
    VQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UE
    AwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4
    MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5
    MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO
    ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0
    aG9yaXR5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sI
    s9CsVw127c0n00ytUINh4qogTQktZAnczomfzD2p7PbPwdzx07HWezcoEStH2jnG
    vDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR1GJk23+jBvGIGGqQ
    Ijy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bIcmfb
    IWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0
    tyA9yn8iNK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97E
    xwzf4TKuzJM7UXiVZ4vuPVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNV
    icQNwZNUMBkTrNN9N6frXTpsNVzbQdcS2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5
    D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e5XOsIzstAL81VXQJSdhJ
    WBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10Yy+xUGUJ
    5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzG
    KAgEJTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB8jCB7zAfBgNVHSMEGDAWgBSg
    EQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rID
    ZsswDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAG
    BgRVHSAAMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwuY29tb2RvY2EuY29t
    L0FBQUNlcnRpZmljYXRlU2VydmljZXMuY3JsMDQGCCsGAQUFBwEBBCgwJjAkBggr
    BgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMA0GCSqGSIb3DQEBDAUA
    A4IBAQAYh1HcdCE9nIrgJ7cz0C7M7PDmy14R3iJvm3WOnnL+5Nb+qh+cli3vA0p+
    rvSNb3I8QzvAP+u431yqqcau8vzY7qN7Q/aGNnwU4M309z/+3ri0ivCRlv79Q2R+
    /czSAaF9ffgZGclCKxO/WIu6pKJmBHaIkU4MiRTOok3JMrO66BQavHHxW/BBC5gA
    CiIDEOUMsfnNkjcZ7Tvx5Dq2+UUTJnWvu6rvP3t3O9LEApE9GQDTF1w52z97GA1F
    zZOFli9d31kWTz9RvdVFGD/tSo7oBmF0Ixa1DVBzJ0RHfxBdiSprhTEUxOipakyA
    vGp4z7h/jnZymQyd/teRCBaho1+V
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCWaDRS5Hr9kD/A
    NK1n0oVi1WkkOu0Le85wC6OrCpVfecgRvINgxiaeov8VXMJc56a13owfVjOyJc8w
    nLhRd7f9BfG1pLHyB/dMElBVyXOnjNXgD3U3o8tIQlnQA6HmiY5OtjPjxN0RWSxq
    yW2jDK2FZmFq98TyaYOlmv6JltsRLib2tLXNBrIJxxpvB/cwymMillaGIkKK51Mp
    QeSZE2EIZzdyrLIzt7gsfxBFMOPv/nhZ9VRRVYoxPsWOQxxu0uyA3tchrHQxQvcc
    JkAml71dKQRiEAo8V/njoK+K/Imxjs5Qqrtxa2uKGADvlCJb67NJcvlaIAekaHt1
    NtnnfZxHAgMBAAECggEAEJ1XNlbt7SermyhWhXMAcBACCtIFkHCvN7pZbJIBOShD
    PQ5VdvG8n2aDBhGWmNuwE0QPt4B2unWpwwV06O7wIJ+w+S9FxuYxX7JgNHHJ+Fa6
    44LhoHFUCdnmgO99yXElirVe2wjKoNl4ah1xIoNKgcNy/HV9SIf2VmteNcW30lha
    5sJB4kdHzxqiKeOELxmWw16crSu2XWKnT59+FjTzq7mY2bz86gGTuDVT6CXgbo97
    IDhP56xizJae3pKm5E7+MGgmnx2+9a5yiezTMUG6AlQywTq8lVxOeMgUfCOUKQxg
    /lLwxCKUiRlNbUC1m0ozh1kMY5WYR0Ui7Sbu499bxQKBgQDOKdAPieqrKVrXWha7
    tdezx1WE4pBOB9GwmXE2MOJp75LNGAHqxq/dV8VlnvM8vsKie0YzBUQoYsXqqpOk
    h8Y+siBO6h61i7inKbNPTOhcSDMf4oTVlY/DYIOyWGiteHFMfU0HbnBnLsj+Qzt5
    3S9yLxqRuYz3j6zcjp9aIWMN3QKBgQC6w/n3qcakroMYnJ5FhNJnm/yoakDDg+Em
    yVr5EN1SYGjlXXvraBAM+zJsGHvnf+GD8pzO8MoYGKVS3UQ8Vl8tctzoG60Aa/UP
    oP+a3aX/v0oxCnZCtEtJVs2p5UrqnFsolWWxEu8coET3g8OdO4CNf/Q8HDL0d+hL
    B9YtDWbKcwKBgCG8+/yfAFVUZjZZ2uCLKKqWE2u0vBLY+rrg0YMhytu1RhvkMuQd
    8cfSRk6UDZBCU43NiLZuxTGqwGLf2VuSkKHP+rOPYsko/WX10A9JMblwY1Vzd3OQ
    jz9U+xhjmXXSARCYbNOrgh+Qq3nYvNH7nXkdNkbky6nzzEEn4fIZBqHNAoGAQCSG
    eRSJ8I0u4QkJIn8XdBYSlBTJ4Vwtu5Bz+g5ctKn/3KZapOK8gHjVPGK8SymUXii4
    yinQfq4YOXlcsgxH6+gDDoRSyk5Jf/CfWKS/GjKsXGNncklRggKZ57ukGydP94Q3
    xLToAkDY7tkGGb4RzIchbnOQ3H1B/mLWn+p2XxkCgYEAvheedlK2QewOzrYdPLJ8
    olh9orNQEDnk2MLAKORHnNz7EoMItEYGOF/y/LT93VY4rwQyAflm+McmoVgeAl6q
    OWyc4VYaQDMvebCVE7ipuf0vca6u7NgZoqA95BNP4HNBCdGe6uFlY1ojdRN9MvMY
    hZaXdCwIL5o0BZPSnljgEIs=
    -----END PRIVATE KEY-----
