kind: UDSBundle
metadata:
  name: istio-test-bundle
  description: A test bundle for istio using k3d as a deployment target
  version: 0.1.0

zarf-packages:
  # Cluster setup
  - name: uds-k3d-dev
    path: build
    ref: 0.1.0
    optional-components:
      - "destroy-cluster"

  # Zarf init required for neuvector currently not working in yolo mode
  - name: init
    repository: ghcr.io/defenseunicorns/packages/init
    ref: v0.29.1

  - name: uds-metallb-dev
    path: build
    ref: 0.1.0

