kind: ZarfPackageConfig
metadata:
  name: uds-metallb-dev
  description: "UDS CI & Developer Metallb Setup"
  url: https://metallb.universe.tf/installation/
  version: 0.1.0

components:
  - name: metallb-config
    required: true
    description: "Install MetalLB to provide a load balancer for the cluster"
    actions:
      onDeploy:
        before:
          - cmd: ./zarf tools kubectl get nodes -o=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}' | cut -d'.' -f1-3
            description: "Load network ip base for MetalLB"
            setVariables:
              - name: BASE_IP
    charts:
      - name: metallb
        url: https://metallb.github.io/metallb
        namespace: metallb-system
        version: 0.13.11
    manifests:
      - name: metallb-config
        files:
          - "metallb.yaml"
    images:
      - quay.io/metallb/controller:v0.13.11
      - quay.io/metallb/speaker:v0.13.11
      - quay.io/frrouting/frr:8.5.2

  - name: haproxy-ingress
    required: true
    description: "Install the haproxy k3d helper"
    manifests:
      - name: haproxy-k3d-helper
        files:
          - "haproxy.yaml"
    images:
      - "cgr.dev/chainguard/haproxy:latest"
