name: Build and Test Istio Capability on k3d

on:
  workflow_dispatch:
    inputs:
      working-dir:
        type: string
        default: '.github/test-infra'
      platform:
        type: string
        default: 'ubuntu-latest'
  workflow_call:
    inputs:
      working-dir:
        type: string
        default: '.github/test-infra'
      platform:
        type: string
        default: 'ubuntu-latest'

jobs:
  test-clean-install:
    runs-on: ${{ inputs.platform }} #ubuntu-latest or macos-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Install Zarf
          uses: defenseunicorns/setup-zarf@main
          with:
            # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
            version: v0.30.1
            download-init-package: true


        - name: Use Node.js latest
          uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
          with:
            node-version: latest
            cache: "npm"
            cache-dependency-path: uds-pepr-istio

        - name: Setup docker (missing on MacOS)
          if: runner.os == 'macos'
          run: |
                brew install docker
                colima start --cpu 2 --memory 10
                # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
                sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

        - name: Install k3d
          run: |
            curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

        - name: Build and Test Capability via Zarf
          shell: bash
          run: zarf package create --confirm
          working-directory: ${{ inputs.working-dir }}